language: python
python:
  - "2.7"
notifications:
    email: false
virtualenv:
    system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:zak-k/iris -y
  - sudo apt-get update -qq -y
  - sudo apt-get install -y python-numpy python-scipy
  - sudo easy_install pyamg
script:
  - cd src && python verify.py 
