language: python
python:
  - "2.7"
notifications:
    email: false
virtualenv:
    system_site_packages: true
before_install:
  - sudo apt-get update -qq -y
  - sudo easy_install numpy scipy pyamg
script:
  - cd src && python verify.py 
