language: python
python:
  - "2.7"
notifications:
    email: false
install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y python-numpy python-scipy
  - sudo easy_install pyamg
script:
  - cd src && python verify.py 
