language: python
python:
  - "2.7"
notifications:
    email: false
virtualenv:
    system_site_packages: true
before_install:
    sudo add-apt-repository ppa:zak-k/ppa-main -y
install:
  - sudo pip install pyamg
script:
  - cd src && python verify.py 
